name: Daily Data Update

on:
  schedule:
    - cron: '30 0 * * *'  # Runs at 00:30 UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull latest changes
      run: |
        git pull origin main --rebase
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Download and process data
      run: |
        python .github/scripts/fetch_data.py

    - name: Commit and push changes
      run: |
        git add data/
        git commit -m "Data update for $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || exit 0
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Handle errors
      if: failure()
      run: |
        echo "::error::Failed to update data. Check the logs for more information."
