name: Daily Data Update

on:
  schedule:
    - cron: '35 0 * * *'  # Runs at 00:30 UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for proper updates
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Download and process data
      run: |
        python .github/scripts/fetch_data.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add data/
        git commit -m "Daily data update $(date +'%Y-%m-%d')" || exit 0
        git push

    - name: Handle errors
      if: failure()
      run: |
        echo "::error::Failed to update data. Check the logs for more information."
